### PR TITLE
Updates for bamboo_phoenix

### PR DESCRIPTION
**Pull request by silvagustin**
### Issue

[Better local preview for text-only emails #5](https://github.com/thoughtbot/bamboo_phoenix/issues/5)

### Changes in this PR

- Updates its dependencies
- Fix a bug
- Updates docs

### CODE REVIEW

**Comment by silvagustin** [comment]
This PR also applies the same changes from [another PR](https://github.com/thoughtbot/bamboo_phoenix/pull/3).

**Comment by silvagustin** [comment]
@germsvel just in case you didn't receive a notification I comment your name here.

**Comment by germsvel** [comment]
Hi @silvagustin, thanks for the work here! I no longer work at thoughtbot or maintain Bamboo. And unfortunately, I don't have write access to this repo.

**Comment by silvagustin** [comment]
> Hi @silvagustin, thanks for the work here! I no longer work at thoughtbot or maintain Bamboo. And unfortunately, I don't have write access to this repo.

Oh, sorry to bother you 😬.

**Comment by germsvel** [comment]
No bother at all! Just sorry I can't help.

**Pull request closed without merging**
